### ISSUE TITLE
Version 0.5.4 is a breaking change. It should be yanked and republished as 0.6

### ISSUE THREAD

**Issue by demurgos** [jmgilman/rustify#19]
The release `0.5.4` includes changes from #17 where the requirement for `http` was changed from `^0.2.6` to `^1.0.0`.

These are breaking changes because `http` is a public dependency (its types are leaking into the types defined by `rustify`) so applying a major semver requirement change on `http` propagates to `rustify`.

As an example, this now breaks [vaultrs](https://github.com/jmgilman/vaultrs) which currently depends on `rustify: ^0.5.2` and `http: ^0.2.9` and assumes unification between its `http` version and the one from `rustify`. See https://github.com/jmgilman/vaultrs/pull/91

I recommend the following actions:
- `rustify 0.5.4` should be yanked immediately
- `rustify 0.6.0` should be released
- Optional: All public dependencies should be re-exported at the lib root and consumers should avoid relying on implicit cargo version unification

**Comment by jmgilman** [comment]
The package is yanked and pushed as `0.6.0`.

**Comment by demurgos** [comment]
Thanks, closing this issue then 🙂
